### ISSUE TITLE
Fix the registration process you absolute freakshow.

### ISSUE THREAD

**Issue by 153** [epicmafia-community-org/EpicMafia#25]
Some awful bug is preventing new users from playing games -- ironically, this makes the site very similar to charley's epicmafia where it became literally impossible for new users to join the site and participate in the community (good luck completing 10 unranked games there lol.) 

Step 1. Create account from home IP address
Step 2. "Your IP address has been flagged as being malicious" 
Step 3. Contact Arcbell through terrible in-site chat system; he ignores me. 
Step 4. Look for e-mail or site Discord; can't find one 
Step 5. Delete account and re-create using different signup method (Discord --> Google)
Step 6. "Your IP address has been flagged..." 
Step 7. Look on the forum for IRC, Discord, e-mail, etc 
Step 8. Find  this git repo and write up this snarky "issue" 

Hey, Arcbell, wise guy -- if you're that paranoid of mass account creation, you can require a captcha or do shit like that. But don't tell me that my home IP address is suspicious, dunce. And make a fucking IRC room or Discord or something, this is ridiculous. 

Yours truly, 
YHWH ( `who#0922` )

**Comment by r3nderer** [comment]
Approved your account. Your IP was flagged by the API we're using.

**Comment by 153** [comment]
luv u arcbell

**Comment by r3nderer** [comment]
This is actually The.
